//! Generated by `scripts/AbilityGenerator.py` from `data/abilities.csv` and
//! `data/ability_effects.csv` — edit the CSVs and re-run the generator.
//!
//! Each function returns a normal [`AbilityDefinition`]; these take precedence over
//! hand-written definitions in `catalog.rs` for the same [`AbilityId`].

#[allow(unused_imports)]
use super::catalog::{nova_ring, shockwave_ring};
#[allow(unused_imports)]
use super::definition::{
    AbilityBehavior, AbilityDefinition, AbilityEffect, AbilityMechanic, AbilityTrigger, AreaCenter,
    AreaRadius, Attribute, DisplacementKind, EffectScaling, EffectTarget, RankValue, StatusSpec,
    TargetTeam, TargetType,
};
#[allow(unused_imports)]
use crate::components::{AbilityId, DamageType};
#[allow(unused_imports)]
use crate::items::StatusKind;
#[allow(unused_imports)]
use crate::scale;

/// CSV-authored definition for `id`, if any.
pub fn definition(id: AbilityId) -> Option<AbilityDefinition> {
    match id {
        AbilityId::SeismicSlam => Some(seismic_slam()),
        AbilityId::ArcaneLance => Some(arcane_lance()),
        AbilityId::Cataclysm => Some(cataclysm()),
        AbilityId::StoneSkin => Some(stone_skin()),
        AbilityId::Overcharge => Some(overcharge()),
        _ => None,
    }
}

// <ability:seismic_slam>
fn seismic_slam() -> AbilityDefinition {
    const DESCRIPTION: &str = "Slams the ground, dealing physical damage to nearby enemies and slowing them by 30% for 1.5s";
    AbilityDefinition::new(AbilityId::SeismicSlam)
        .description(DESCRIPTION)
        .targeting(
            TargetType::NoTarget,
            RankValue::ZERO,
            RankValue::from_level_1(220.0, 15.0),
        )
        .team(TargetTeam::Enemy)
        .costs(
            RankValue::from_level_1(10.0, -0.4),
            RankValue::from_level_1(55.0, 8.0),
        )
        .timing(0.25, 0.35)
        .mechanic(shockwave_ring())
        .on(
            AbilityTrigger::OnCast,
            EffectTarget::UnitsInRadius {
                center: AreaCenter::Caster,
                radius: AreaRadius::Ability,
                team: TargetTeam::Enemy,
            },
            AbilityEffect::Damage {
                amount: RankValue::from_level_1(80.0, 30.0),
                damage_type: DamageType::Physical,
                scaling: EffectScaling::None,
            },
        )
        .on(
            AbilityTrigger::OnCast,
            EffectTarget::UnitsInRadius {
                center: AreaCenter::Caster,
                radius: AreaRadius::Ability,
                team: TargetTeam::Enemy,
            },
            AbilityEffect::ApplyStatus {
                status: StatusSpec::Slow {
                    percent: RankValue::fixed(30.0),
                },
                duration: RankValue::fixed(1.5),
            },
        )
}
// </ability:seismic_slam>

// <ability:arcane_lance>
fn arcane_lance() -> AbilityDefinition {
    const DESCRIPTION: &str =
        "Fires a magical bolt at the target; deals 25% bonus damage to targets below 35% health";
    AbilityDefinition::new(AbilityId::ArcaneLance)
        .description(DESCRIPTION)
        .targeting(
            TargetType::Unit,
            RankValue::from_level_1(500.0, 20.0),
            RankValue::ZERO,
        )
        .team(TargetTeam::Enemy)
        .costs(
            RankValue::from_level_1(7.0, -0.3),
            RankValue::from_level_1(50.0, 7.0),
        )
        .timing(0.2, 0.3)
        .mechanic(AbilityMechanic::Projectile {
            splash_radius: AreaRadius::Ability,
            speed: None,
            skillshot: false,
        })
        .on(
            AbilityTrigger::OnProjectileHit,
            EffectTarget::TriggerUnit,
            AbilityEffect::Damage {
                amount: RankValue::from_level_1(95.0, 32.0),
                damage_type: DamageType::Magical,
                scaling: EffectScaling::None,
            },
        )
        .on(
            AbilityTrigger::OnProjectileHit,
            EffectTarget::TriggerUnit,
            AbilityEffect::Damage {
                amount: RankValue::from_level_1(23.75, 8.0),
                damage_type: DamageType::Magical,
                scaling: EffectScaling::TargetHealthBelow(0.35),
            },
        )
}
// </ability:arcane_lance>

// <ability:cataclysm>
fn cataclysm() -> AbilityDefinition {
    const DESCRIPTION: &str =
        "Calls down a cataclysm, dealing magical damage in an area and stunning enemies for 1.2s";
    AbilityDefinition::new(AbilityId::Cataclysm)
        .description(DESCRIPTION)
        .targeting(
            TargetType::Area,
            RankValue::from_level_1(550.0, 15.0),
            RankValue::from_level_1(320.0, 20.0),
        )
        .team(TargetTeam::Enemy)
        .costs(
            RankValue::from_level_1(55.0, -5.0),
            RankValue::from_level_1(120.0, 25.0),
        )
        .timing(0.4, 0.45)
        .mechanic(nova_ring())
        .on(
            AbilityTrigger::OnCast,
            EffectTarget::UnitsInRadius {
                center: AreaCenter::Aim,
                radius: AreaRadius::Ability,
                team: TargetTeam::Enemy,
            },
            AbilityEffect::Damage {
                amount: RankValue::from_level_1(200.0, 70.0),
                damage_type: DamageType::Magical,
                scaling: EffectScaling::None,
            },
        )
        .on(
            AbilityTrigger::OnCast,
            EffectTarget::UnitsInRadius {
                center: AreaCenter::Aim,
                radius: AreaRadius::Ability,
                team: TargetTeam::Enemy,
            },
            AbilityEffect::ApplyStatus {
                status: StatusSpec::Stun,
                duration: RankValue::fixed(1.2),
            },
        )
}
// </ability:cataclysm>

// <ability:stone_skin>
fn stone_skin() -> AbilityDefinition {
    const DESCRIPTION: &str = "Permanently gain +4 armor per rank while learned";
    AbilityDefinition::new(AbilityId::StoneSkin)
        .description(DESCRIPTION)
        .behavior(AbilityBehavior::Passive)
        .targeting(TargetType::NoTarget, RankValue::ZERO, RankValue::ZERO)
        .team(TargetTeam::Ally)
        .costs(RankValue::ZERO, RankValue::ZERO)
        .timing(0.0, 0.25)
}
// </ability:stone_skin>

// <ability:overcharge>
fn overcharge() -> AbilityDefinition {
    const DESCRIPTION: &str = "While on, drain 8 mana/sec and gain +20% attack speed and +10 move speed; turns off when out of mana";
    AbilityDefinition::new(AbilityId::Overcharge)
        .description(DESCRIPTION)
        .behavior(AbilityBehavior::Toggle)
        .targeting(TargetType::NoTarget, RankValue::ZERO, RankValue::ZERO)
        .team(TargetTeam::Ally)
        .costs(RankValue::fixed(1.0), RankValue::from_level_1(15.0, 3.0))
        .timing(0.0, 0.0)
}
// </ability:overcharge>
