#!/usr/bin/env python3
"""AbilityGenerator — build ability definitions from CSV.

Reads `abilities.csv` (identity, targeting, costs, timing, projectile) and
`ability_effects.csv` (trigger-tagged consequences, joined on `ability_id`),
validates both, and generates normal `AbilityDefinition`s:

  - `src/abilities/generated.rs`: one `fn <id>() -> AbilityDefinition` per ability,
    built with the same builders / `AbilityEffectEntry` rows as hand-written abilities
    in `src/abilities/catalog.rs`. Generated definitions take precedence over
    hand-written ones with the same `AbilityId`.
  - `src/components.rs`: `AbilityId` variant, display name, ultimate flag, max rank.

Re-running overwrites abilities that already exist; abilities missing from the CSV
are kept. Blank cells mean "not applicable"; `75|150|225|300` gives one value per level.

Usage:
  python3 scripts/AbilityGenerator.py                       # data/abilities.csv + data/ability_effects.csv
  python3 scripts/AbilityGenerator.py my_abilities.csv my_effects.csv
  python3 scripts/AbilityGenerator.py --check                # validate only
  python3 scripts/AbilityGenerator.py --dry-run              # print generated code
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generator_common import (  # noqa: E402
    EFFECT_COLUMNS,
    EffectContext,
    EffectRow,
    Report,
    Row,
    check_id,
    effect_to_rust,
    f32,
    parse_effect_rows,
    parse_enum,
    parse_number,
    parse_scalar,
    rank_value,
    read_blocks,
    read_csv,
    region_body,
    replace_region,
    rust_fn_name,
    rust_str,
    rustfmt,
    to_pascal_case,
    upsert_line,
)

ABILITY_COLUMNS = (
    "id",
    "name",
    "slot",
    "ability_type",
    "target_type",
    "target_team",
    "cast_range",
    "aoe_radius",
    "cast_time",
    "channel_time",
    "cooldown",
    "mana_cost",
    "max_charges",
    "charge_restore_time",
    "projectile_type",
    "projectile_speed",
    "description",
)
# Optional extras: cast_backswing (default 0.25), max_rank (default from level counts / slot).

SLOTS = ("q", "w", "e", "r", "innate")
ABILITY_TYPES = {"active": "Active", "passive": "Passive", "toggle": "Toggle"}
TARGET_TYPES = ("unit", "point", "direction", "no_target", "self")
TARGET_TEAMS = {"enemy": "Enemy", "ally": "Ally", "both": "Any", "self": "Ally"}
PROJECTILE_TYPES = ("none", "targeted", "skillshot")
LEVEL_FIELDS = ("cast_range", "aoe_radius", "cooldown", "mana_cost")
EFFECT_LEVEL_FIELDS = ("value", "duration", "amount", "radius")
DEFAULT_BACKSWING = 0.25

GENERATED_HEADER = """\
//! Generated by `scripts/AbilityGenerator.py` from `data/abilities.csv` and
//! `data/ability_effects.csv` — edit the CSVs and re-run the generator.
//!
//! Each function returns a normal [`AbilityDefinition`]; these take precedence over
//! hand-written definitions in `catalog.rs` for the same [`AbilityId`].

#[allow(unused_imports)]
use super::catalog::{nova_ring, shockwave_ring};
#[allow(unused_imports)]
use super::definition::{
    AbilityBehavior, AbilityDefinition, AbilityEffect, AbilityMechanic, AbilityTrigger,
    AreaCenter, AreaRadius, Attribute, DisplacementKind, EffectScaling, EffectTarget, RankValue,
    StatusSpec, TargetTeam, TargetType,
};
#[allow(unused_imports)]
use crate::components::{AbilityId, DamageType};
#[allow(unused_imports)]
use crate::items::StatusKind;
#[allow(unused_imports)]
use crate::scale;
"""


@dataclass
class Ability:
    row: Row
    id: str
    variant: str
    name: str
    slot: str
    behavior: str
    target_type: str
    target_team: str
    rust_target_type: str
    cast_range: list[float] | None
    aoe_radius: list[float] | None
    cast_time: float
    backswing: float
    channel_time: float | None
    cooldown: list[float] | None
    mana_cost: list[float] | None
    max_charges: int | None
    charge_restore_time: float | None
    projectile: str
    projectile_speed: float | None
    description: str
    max_rank: int
    effects: list[str] = field(default_factory=list)


def level_count(row: Row, names: tuple[str, ...]) -> list[tuple[str, int]]:
    return [(n, len(row.get(n).split("|"))) for n in names if "|" in row.get(n)]


def parse_ability(row: Row, effect_rows: list[EffectRow], report: Report) -> Ability | None:
    ident = check_id(row, "id", report)
    name = row.get("name")
    if not name:
        report.error(row.file, row.line, "name", "", "required")
    slot = parse_enum(row, "slot", SLOTS, report)
    ability_type = parse_enum(row, "ability_type", list(ABILITY_TYPES), report)
    target_type = parse_enum(row, "target_type", TARGET_TYPES, report)
    target_team = parse_enum(row, "target_team", list(TARGET_TEAMS), report)
    projectile = parse_enum(row, "projectile_type", PROJECTILE_TYPES, report, required=False) or "none"

    # Level count: explicit max_rank, else the first level-dependent field, else by slot.
    counts = level_count(row, LEVEL_FIELDS) + [
        (f"{e.row.file}:{e.row.line} {n}", c) for e in effect_rows for n, c in level_count(e.row, EFFECT_LEVEL_FIELDS)
    ]
    explicit = parse_scalar(row, "max_rank", report, integer=True, minimum=1)
    max_rank = int(explicit) if explicit else (counts[0][1] if counts else (4 if slot == "r" else 7))
    for where, count in level_count(row, LEVEL_FIELDS):
        if count != max_rank:
            report.error(row.file, row.line, where, row.get(where), f"has {count} levels; expected {max_rank} (max_rank)")

    cast_range = parse_number(row, "cast_range", report, levels=True, minimum=0)
    aoe_radius = parse_number(row, "aoe_radius", report, levels=True, minimum=0)
    cooldown = parse_number(row, "cooldown", report, levels=True, minimum=0)
    mana_cost = parse_number(row, "mana_cost", report, levels=True, minimum=0)
    cast_time = parse_scalar(row, "cast_time", report, minimum=0) or 0.0
    backswing = parse_scalar(row, "cast_backswing", report, minimum=0)
    channel_time = parse_scalar(row, "channel_time", report, minimum=0)
    max_charges = parse_scalar(row, "max_charges", report, integer=True, minimum=1)
    restore = parse_scalar(row, "charge_restore_time", report, minimum=0)
    speed = parse_scalar(row, "projectile_speed", report, minimum=1)
    # Keep going after value errors so effect rows are still validated; only the
    # identifying enums are needed to interpret them.
    if None in (ident, slot, ability_type, target_type, target_team) or not name:
        return None

    def err(fld: str, message: str) -> None:
        report.error(row.file, row.line, fld, row.get(fld), message)

    if cast_time > 0.5:
        report.warn(row.file, row.line, "cast_time", row.get("cast_time"), "cast point is capped at 0.5s")
    if restore is not None and max_charges is None:
        err("charge_restore_time", "charge_restore_time requires max_charges")
    if max_charges is not None and restore is None:
        err("max_charges", "charge-based abilities need a charge_restore_time")
    if speed is not None and projectile == "none":
        err("projectile_speed", "projectile_speed requires projectile_type targeted or skillshot")
    if projectile == "targeted" and target_type != "unit":
        err("projectile_type", f"targeted projectiles home in on a unit; target_type is {target_type}")
    if projectile == "skillshot" and target_type not in ("point", "direction"):
        err("projectile_type", f"skillshots fly toward a point or direction; target_type is {target_type}")
    if target_team == "self" and target_type not in ("self", "no_target"):
        err("target_team", f"target_team self requires target_type self or no_target (got {target_type})")
    if target_type == "self" and target_team != "self":
        err("target_team", "target_type self requires target_team self")
    if target_type in ("unit", "point", "direction") and not cast_range and ability_type != "passive":
        err("cast_range", f"required for {target_type}-targeted abilities")
    if ability_type == "passive":
        if target_type not in ("no_target", "self"):
            err("target_type", "passive abilities cannot be targeted; use no_target or self")
        if projectile != "none":
            err("projectile_type", "passive abilities cannot launch projectiles")
        for fld in ("cooldown", "mana_cost", "cast_time", "channel_time", "max_charges"):
            if row.get(fld) and any(v != 0 for v in parse_number(row, fld, Report(), levels=True) or []):
                report.warn(row.file, row.line, fld, row.get(fld), "ignored: passive abilities are never cast")
    if ability_type == "toggle" and target_type not in ("no_target", "self"):
        err("target_type", "toggle abilities use no_target or self")

    if target_type == "unit":
        rust_target = "Unit"
    elif target_type == "point" and projectile == "none" and aoe_radius and any(aoe_radius):
        rust_target = "Area"
    elif target_type in ("point", "direction"):
        rust_target = "Point"
    else:
        rust_target = "NoTarget"

    return Ability(
        row=row,
        id=ident,
        variant=to_pascal_case(ident),
        name=name,
        slot=slot,
        behavior=ABILITY_TYPES[ability_type],
        target_type=target_type,
        target_team=target_team,
        rust_target_type=rust_target,
        cast_range=cast_range,
        aoe_radius=aoe_radius,
        cast_time=cast_time,
        backswing=DEFAULT_BACKSWING if backswing is None else backswing,
        channel_time=channel_time,
        cooldown=cooldown,
        mana_cost=mana_cost,
        max_charges=int(max_charges) if max_charges else None,
        charge_restore_time=restore,
        projectile=projectile,
        projectile_speed=speed,
        description=row.get("description"),
        max_rank=max_rank,
    )


def effect_context(a: Ability) -> EffectContext:
    on_cast_center = "Caster" if a.rust_target_type == "NoTarget" else "Aim"
    ctx = EffectContext(
        kind="ability",
        owner_id=a.id,
        levels=a.max_rank,
        center_for={"on_cast": on_cast_center},
        team=TARGET_TEAMS[a.target_team],
        has_aoe=bool(a.aoe_radius and any(a.aoe_radius)) or a.projectile == "skillshot",
    )
    if a.behavior == "Passive":
        for trigger in ("on_cast", "on_projectile_hit", "on_impact", "on_channel_tick", "on_channel_end"):
            ctx.invalid_trigger[trigger] = "passive abilities are never cast, so this trigger never fires"
    if a.projectile == "none":
        for trigger in ("on_projectile_hit", "on_impact"):
            ctx.invalid_trigger[trigger] = "the ability has no projectile (projectile_type none)"
    if not a.channel_time:
        for trigger in ("on_channel_tick", "on_channel_end"):
            ctx.invalid_trigger[trigger] = "the ability is not channelled (channel_time blank)"
    if a.target_type != "unit":
        for trigger in ("on_cast", "on_projectile_hit", "on_unit_contact", "on_impact", "on_channel_tick", "on_channel_end", "on_expire"):
            ctx.invalid_combo[(trigger, "cast_target")] = f"cast_target requires target_type unit (got {a.target_type})"
        ctx.invalid_combo[("on_cast", "trigger_unit")] = f"on_cast only has a trigger unit for unit-targeted abilities (got {a.target_type})"
    ctx.invalid_combo[("on_cast", "affected_units")] = "on_cast has no affected units; use units_in_radius"
    ctx.invalid_combo[("on_impact", "trigger_unit")] = "on_impact fires when the projectile hit no unit; use affected_units or units_in_radius"
    for trigger in ("on_channel_tick", "on_channel_end"):
        ctx.invalid_combo[(trigger, "trigger_unit")] = f"{trigger} has no trigger unit"
        ctx.invalid_combo[(trigger, "affected_units")] = f"{trigger} has no affected units"
    if a.projectile == "skillshot":
        ctx.invalid_combo[("on_projectile_hit", "affected_units")] = "skillshots report each unit they pass as trigger_unit (no splash)"
    return ctx


def ability_fn(a: Ability) -> str:
    lines = [f"// <ability:{a.id}>", f"fn {rust_fn_name(a.id)}() -> AbilityDefinition {{"]
    # Kept out of the builder chain so rustfmt can still wrap the chain.
    if a.description:
        lines.append(f"    const DESCRIPTION: &str = {rust_str(a.description)};")
    lines.append(f"    AbilityDefinition::new(AbilityId::{a.variant})")
    if a.description:
        lines.append("        .description(DESCRIPTION)")
    if a.behavior != "Active":
        lines.append(f"        .behavior(AbilityBehavior::{a.behavior})")
    aoe = rank_value(a.aoe_radius)
    if a.projectile == "skillshot" and not (a.aoe_radius and any(a.aoe_radius)):
        aoe = "RankValue::fixed(scale::ABILITY_PROJECTILE_WIDTH)"
    lines.append(f"        .targeting(TargetType::{a.rust_target_type}, {rank_value(a.cast_range)}, {aoe})")
    lines.append(f"        .team(TargetTeam::{TARGET_TEAMS[a.target_team]})")
    lines.append(f"        .costs({rank_value(a.cooldown)}, {rank_value(a.mana_cost)})")
    lines.append(f"        .timing({f32(a.cast_time)}, {f32(a.backswing)})")
    if a.channel_time:
        lines.append(f"        .channel({f32(a.channel_time)})")
    if a.max_charges:
        lines.append(f"        .charges({a.max_charges}, {f32(a.charge_restore_time or 0.0)})")
    if a.projectile != "none":
        speed = f"Some({f32(a.projectile_speed)})" if a.projectile_speed else "None"
        skillshot = "true" if a.projectile == "skillshot" else "false"
        lines.append(
            "        .mechanic(AbilityMechanic::Projectile { "
            f"splash_radius: AreaRadius::Ability, speed: {speed}, skillshot: {skillshot} }})"
        )
    elif a.behavior == "Active" and a.aoe_radius and any(a.aoe_radius):
        if a.rust_target_type == "NoTarget":
            lines.append("        .mechanic(shockwave_ring())")
        elif a.rust_target_type == "Area":
            lines.append("        .mechanic(nova_ring())")
    for effect in a.effects:
        lines.append(f"        .on({effect})")
    lines += ["}", f"// </ability:{a.id}>"]
    return "\n".join(lines) + "\n"


def render_generated(blocks: dict[str, str]) -> str:
    import re

    arms = []
    for ident, block in blocks.items():
        variant = re.search(r"AbilityDefinition::new\(AbilityId::(\w+)\)", block)
        if variant:
            arms.append(f"        AbilityId::{variant.group(1)} => Some({rust_fn_name(ident)}()),")
    out = [GENERATED_HEADER]
    out.append("/// CSV-authored definition for `id`, if any.")
    out.append("pub fn definition(id: AbilityId) -> Option<AbilityDefinition> {")
    out.append("    match id {")
    out += arms
    out.append("        _ => None,")
    out.append("    }")
    out.append("}\n")
    out += [block.rstrip("\n") + "\n" for block in blocks.values()]
    return "\n".join(out)


def patch_components(components_rs: str, abilities: list[Ability]) -> str:
    import re

    existing = set(re.findall(r"^\s*([A-Z][A-Za-z0-9]*)\s*,", region_body(components_rs, "hero_generator", "ability_enum"), re.MULTILINE))
    for a in abilities:
        if a.variant not in existing:
            body = region_body(components_rs, "hero_generator", "ability_enum")
            body += f"    // AbilityGenerator: {a.name}\n    {a.variant},\n"
            components_rs = replace_region(components_rs, "hero_generator", "ability_enum", body)
            existing.add(a.variant)
        components_rs = upsert_line(
            components_rs,
            "hero_generator",
            "ability_display_name",
            rf"AbilityId::{a.variant}\s*=>",
            f"            AbilityId::{a.variant} => {rust_str(a.name)},",
        )
        components_rs = upsert_line(
            components_rs,
            "ability_generator",
            "max_rank",
            rf"AbilityId::{a.variant}\s*=>",
            f"            AbilityId::{a.variant} => {a.max_rank},",
        )
        ults = region_body(components_rs, "hero_generator", "ability_ultimates")
        tokens = [t.strip() for t in ults.replace("\n", " ").split("|") if t.strip()]
        token = f"AbilityId::{a.variant}"
        if a.slot == "r" and token not in tokens:
            tokens.append(token)
        elif a.slot != "r" and token in tokens:
            tokens.remove(token)
        components_rs = replace_region(
            components_rs, "hero_generator", "ability_ultimates", "            " + " | ".join(tokens) + "\n"
        )
    return components_rs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    repo_default = Path(__file__).resolve().parents[1]
    parser.add_argument("abilities", type=Path, nargs="?", help="abilities CSV (default: data/abilities.csv)")
    parser.add_argument("effects", type=Path, nargs="?", help="ability effects CSV (default: data/ability_effects.csv)")
    parser.add_argument("--repo-root", type=Path, default=repo_default, help="repository root (default: parent of scripts/)")
    parser.add_argument("--check", action="store_true", help="validate the CSVs without writing anything")
    parser.add_argument("--dry-run", action="store_true", help="print the generated Rust instead of writing it")
    args = parser.parse_args()

    repo = args.repo_root.resolve()
    abilities_csv = args.abilities or repo / "data" / "abilities.csv"
    effects_csv = args.effects or repo / "data" / "ability_effects.csv"

    abilities, report = load(abilities_csv, effects_csv)
    report.fail_if_errors()
    report.print()
    print(f"Validated {len(abilities)} abilit{'y' if len(abilities) == 1 else 'ies'} "
          f"with {sum(len(a.effects) for a in abilities)} effect row(s).")
    if args.check:
        return 0

    generated_path = repo / "src" / "abilities" / "generated.rs"
    components_path = repo / "src" / "components.rs"
    blocks = read_blocks(generated_path, "ability")
    for a in abilities:
        verb = "update" if a.id in blocks else "add"
        print(f"  {verb}: {a.id} → AbilityId::{a.variant} ({a.behavior}, {a.rust_target_type}, "
              f"ranks={a.max_rank}, effects={len(a.effects)})")
        blocks[a.id] = ability_fn(a)
    generated = render_generated(blocks)
    components_rs = patch_components(components_path.read_text(encoding="utf-8"), abilities)

    if args.dry_run:
        print(generated)
        print("Dry run — no files written.")
        return 0
    generated_path.write_text(generated, encoding="utf-8")
    rustfmt(generated_path)
    components_path.write_text(components_rs, encoding="utf-8")
    print(f"Wrote {generated_path.relative_to(repo)} and updated {components_path.relative_to(repo)}")
    return 0


def load(abilities_csv: Path, effects_csv: Path) -> tuple[list[Ability], Report]:
    report = Report()
    ability_rows = read_csv(abilities_csv, ABILITY_COLUMNS, report, legacy_hint="Ability_name")
    effect_rows = read_csv(effects_csv, ("ability_id", *EFFECT_COLUMNS), report)

    ids: dict[str, int] = {}
    names: dict[str, int] = {}
    variants: dict[str, str] = {}
    for row in ability_rows:
        ident, name = row.get("id"), row.get("name").casefold()
        if ident in ids:
            report.error(row.file, row.line, "id", ident, f"duplicate ability id (first defined on line {ids[ident]})")
        elif ident:
            ids[ident] = row.line
            variant = to_pascal_case(ident)
            if variant in variants:
                report.error(row.file, row.line, "id", ident, f"maps to AbilityId::{variant}, same as {variants[variant]!r}")
            variants[variant] = ident
        if name and name in names:
            report.error(row.file, row.line, "name", row.get("name"), f"duplicate ability name (first used on line {names[name]})")
        elif name:
            names[name] = row.line

    by_owner = parse_effect_rows(effect_rows, "ability_id", set(ids), report)
    abilities: list[Ability] = []
    seen: set[str] = set()
    for row in ability_rows:
        if row.get("id") in seen:
            continue
        seen.add(row.get("id"))
        ability = parse_ability(row, by_owner.get(row.get("id"), []), report)
        if ability is None:
            continue
        ctx = effect_context(ability)
        for effect in by_owner.get(ability.id, []):
            rendered = effect_to_rust(effect, ctx, report)
            if rendered:
                ability.effects.append(", ".join(rendered))
        if not by_owner.get(ability.id) and ability.behavior != "Passive":
            report.warn(row.file, row.line, "id", ability.id, "no rows in the effects CSV; the ability has no consequences")
        abilities.append(ability)
    return abilities, report


if __name__ == "__main__":
    raise SystemExit(main())
