#!/usr/bin/env python3
"""ItemGenerator — build item definitions from CSV.

Reads `items.csv` (identity / economy / inventory rules) and `item_effects.csv`
(trigger-tagged consequences, joined on `item_id`), validates both, and generates:

  - `src/item_catalog.rs`: one `static ItemDefinition` per item. Its `effects` are the
    same `AbilityEffectEntry` rows abilities use, resolved by the shared trigger pipeline
    (`passive` stat bonuses are applied on purchase).
  - `src/items.rs`: `ItemId` variant and shop order (`ItemId::all`).

Re-running overwrites items that already exist; items missing from the CSV are kept.
Blank cells mean "not applicable".

Optional extra columns (kept from the previous generator format): `short_label`,
`cooldown` (active cooldown in seconds), `components` (`;`-separated item ids),
`color_r` / `color_g` / `color_b` (0..1).

Usage:
  python3 scripts/ItemGenerator.py                     # data/items.csv + data/item_effects.csv
  python3 scripts/ItemGenerator.py my_items.csv my_item_effects.csv
  python3 scripts/ItemGenerator.py --check              # validate only
  python3 scripts/ItemGenerator.py --dry-run            # print generated code
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from generator_common import (  # noqa: E402
    EFFECT_COLUMNS,
    EffectContext,
    EffectRow,
    Report,
    Row,
    check_id,
    effect_to_rust,
    f32,
    parse_bool,
    parse_effect_rows,
    parse_enum,
    parse_scalar,
    read_blocks,
    read_csv,
    region_body,
    replace_region,
    rust_str,
    rustfmt,
    to_pascal_case,
    upsert_line,
)

ITEM_COLUMNS = (
    "id",
    "name",
    "item_type",
    "cost",
    "sell_value",
    "tier",
    "rarity",
    "stackable",
    "max_stack",
    "consumable",
    "max_charges",
    "description",
)

ITEM_TYPES = {
    "component": "Component",
    "weapon": "Weapon",
    "armor": "Armor",
    "accessory": "Accessory",
    "consumable": "Consumable",
    "utility": "Utility",
    "recipe": "Recipe",
}
RARITIES = {r: r.capitalize() for r in ("common", "uncommon", "rare", "epic", "legendary")}
MAX_COMPONENTS = 5
NOT_EMITTED = {
    "on_damage_taken": "not emitted by the game yet; the effect will never fire",
    "on_kill": "not emitted by the game yet; the effect will never fire",
    "on_death": "not emitted by the game yet; the effect will never fire",
}

STAT_LABELS = {
    "max_health": "HP",
    "health": "HP",
    "health_regen": "HP Regen",
    "max_mana": "Mana",
    "mana": "Mana",
    "mana_regen": "Mana Regen",
    "attack_damage": "Attack Damage",
    "attack_speed": "Attack Speed",
    "armor": "Armor",
    "magic_resist": "Magic Resist",
    "move_speed": "Move Speed",
    "strength": "Strength",
    "agility": "Agility",
    "intelligence": "Intelligence",
}

GENERATED_HEADER = """\
//! Generated by `scripts/ItemGenerator.py` from `data/items.csv` and
//! `data/item_effects.csv` — edit the CSVs and re-run the generator.

#[allow(unused_imports)]
use crate::abilities::definition::{
    AbilityEffect, AbilityEffectEntry, AbilityTrigger, AreaCenter, AreaRadius, Attribute,
    DisplacementKind, EffectScaling, EffectTarget, PassiveStat, RankValue, StatusSpec, TargetTeam,
};
#[allow(unused_imports)]
use crate::components::DamageType;
#[allow(unused_imports)]
use crate::items::{ItemDefinition, ItemId, ItemRarity, ItemType, StatusKind};
"""


@dataclass
class Item:
    row: Row
    id: str
    variant: str
    name: str
    short_label: str
    item_type: str
    cost: int
    sell_value: int
    tier: int
    rarity: str
    max_stack: int
    consumable: bool
    max_charges: int | None
    cooldown: float
    components: list[str]
    color: tuple[float, float, float]
    description: str
    effects: list[tuple[str, str, str]] = field(default_factory=list)


def short_label_from_name(name: str) -> str:
    parts = re.findall(r"[A-Za-z0-9]+", name)
    if not parts:
        return "IT"
    if len(parts) == 1:
        return parts[0][:2].upper()
    return "".join(p[0] for p in parts[:3]).upper()


def color_from_name(name: str) -> tuple[float, float, float]:
    digest = hashlib.sha256(name.encode("utf-8")).digest()
    return tuple(round(0.25 + (digest[i] / 255.0) * 0.6, 3) for i in range(3))  # type: ignore[return-value]


def describe(effects: list[EffectRow]) -> str:
    bits = []
    for e in effects:
        if e.trigger == "passive" and e.effect_type == "stat_modifier":
            stat = e.row.get("effect_id").lower()
            bits.append(f"+{e.row.get('value')} {STAT_LABELS.get(stat, stat)}")
    return ", ".join(bits)


def parse_item(row: Row, effects: list[EffectRow], report: Report) -> Item | None:
    ident = check_id(row, "id", report)
    name = row.get("name")
    if not name:
        report.error(row.file, row.line, "name", "", "required")
    item_type = parse_enum(row, "item_type", list(ITEM_TYPES), report)
    rarity = parse_enum(row, "rarity", list(RARITIES), report, required=False) or "common"
    cost = parse_scalar(row, "cost", report, integer=True, minimum=0)
    if not row.get("cost"):
        report.error(row.file, row.line, "cost", "", "required")
    sell_value = parse_scalar(row, "sell_value", report, integer=True, minimum=0)
    tier = parse_scalar(row, "tier", report, integer=True, minimum=1)
    stackable = parse_bool(row, "stackable", report) or False
    max_stack = parse_scalar(row, "max_stack", report, integer=True, minimum=1)
    consumable = parse_bool(row, "consumable", report) or False
    max_charges = parse_scalar(row, "max_charges", report, integer=True, minimum=1)
    cooldown = parse_scalar(row, "cooldown", report, minimum=0)
    color = [parse_scalar(row, f"color_{c}", report, minimum=0) for c in "rgb"]
    if ident is None or not name:
        return None

    def err(fld: str, message: str) -> None:
        report.error(row.file, row.line, fld, row.get(fld), message)

    has_use = any(e.trigger == "on_use" for e in effects)
    if stackable and max_stack is None:
        err("max_stack", "required for stackable items")
    if stackable and max_stack is not None and max_stack < 2:
        err("max_stack", "stackable items need max_stack >= 2")
    if not stackable and max_stack is not None:
        err("max_stack", "only stackable items have a max_stack")
    if consumable and not has_use:
        err("consumable", "consumable items need on_use effects in the item effects CSV")
    if max_charges is not None and not consumable:
        report.warn(row.file, row.line, "max_charges", row.get("max_charges"), "charges are only spent by consumable items")
    if item_type == "consumable" and not consumable:
        report.warn(row.file, row.line, "item_type", row.get("item_type"), "item_type consumable but consumable is false")
    if sell_value is not None and cost is not None and sell_value > cost:
        report.warn(row.file, row.line, "sell_value", row.get("sell_value"), "sell value exceeds cost")
    if has_use and cooldown is None:
        report.warn(row.file, row.line, "cooldown", "", "on_use item without a cooldown column value; using 0s")
    if cooldown is not None and not has_use:
        report.warn(row.file, row.line, "cooldown", row.get("cooldown"), "ignored: the item has no on_use effects")
    if any(c is not None and c > 1 for c in color):
        err("color_r", "colors are 0..1 floats")
    if any(c is None for c in color) and any(c is not None for c in color):
        err("color_r", "set all of color_r, color_g, color_b or none")
    short = row.get("short_label") or short_label_from_name(name)
    if len(short) > 4:
        err("short_label", "at most 4 characters")
    components = [c.strip() for c in re.split(r"[;|]", row.get("components")) if c.strip()]
    if len(components) > MAX_COMPONENTS:
        err("components", f"at most {MAX_COMPONENTS} recipe components")
    return Item(
        row=row,
        id=ident,
        variant=to_pascal_case(ident),
        name=name,
        short_label=short,
        item_type=ITEM_TYPES.get(item_type or "", "Utility"),
        cost=int(cost or 0),
        sell_value=int(sell_value) if sell_value is not None else int(cost or 0) // 2,
        tier=int(tier) if tier else 1,
        rarity=RARITIES[rarity],
        max_stack=int(max_stack) if stackable and max_stack else 1,
        consumable=consumable,
        max_charges=int(max_charges) if max_charges else None,
        cooldown=cooldown or 0.0,
        components=components,
        color=tuple(color) if all(c is not None for c in color) else color_from_name(name),  # type: ignore[arg-type]
        description=row.get("description") or describe(effects),
    )


def effect_context(item: Item) -> EffectContext:
    ctx = EffectContext(
        kind="item",
        owner_id=item.id,
        levels=None,
        center_for={"on_use": "Caster", "passive": "Caster"},
    )
    for trigger in ("passive", "on_use", "on_attack", "on_attack_hit", "on_damage_taken", "on_kill", "on_death"):
        ctx.invalid_combo[(trigger, "cast_target")] = "items have no cast target (no item targeting yet)"
    for target in ("trigger_unit", "affected_units", "attacker", "units_in_radius"):
        ctx.invalid_combo[("passive", target)] = "passive bonuses apply to the owner"
    for target in ("trigger_unit", "affected_units", "attacker"):
        ctx.invalid_combo[("on_use", target)] = f"on_use has no {target.replace('_', ' ')}; use owner or units_in_radius"
    for trigger in ("on_attack", "on_attack_hit", "on_damage_taken", "on_kill", "on_death"):
        ctx.invalid_combo[(trigger, "affected_units")] = f"{trigger} has no affected units; use units_in_radius"
    return ctx


def item_static(item: Item) -> str:
    const = item.id.upper()
    r, g, b = item.color
    components = ", ".join(f"ItemId::{to_pascal_case(c)}" for c in item.components)
    lines = [
        f"// <item:{item.id}>",
        f"static {const}: ItemDefinition = ItemDefinition {{",
        f"    id: ItemId::{item.variant},",
        f"    name: {rust_str(item.name)},",
        f"    short_label: {rust_str(item.short_label)},",
        f"    item_type: ItemType::{item.item_type},",
        f"    cost: {item.cost},",
        f"    sell_value: {item.sell_value},",
        f"    tier: {item.tier},",
        f"    rarity: ItemRarity::{item.rarity},",
        f"    max_stack: {item.max_stack},",
        f"    consumable: {'true' if item.consumable else 'false'},",
        f"    max_charges: {f'Some({item.max_charges})' if item.max_charges else 'None'},",
        f"    cooldown: {f32(item.cooldown)},",
        f"    components: &[{components}],",
        f"    color: [{f32(r)}, {f32(g)}, {f32(b)}],",
        f"    description: {rust_str(item.description)},",
        "    effects: &[",
    ]
    for trigger, target, effect in item.effects:
        lines.append(f"        AbilityEffectEntry {{ trigger: {trigger}, target: {target}, effect: {effect} }},")
    lines += ["    ],", "};", f"// </item:{item.id}>"]
    return "\n".join(lines) + "\n"


def render_generated(blocks: dict[str, str]) -> str:
    out = [GENERATED_HEADER]
    out.append("pub fn definition(id: ItemId) -> &'static ItemDefinition {")
    out.append("    match id {")
    for ident, block in blocks.items():
        variant = re.search(r"id: ItemId::(\w+),", block)
        if variant:
            out.append(f"        ItemId::{variant.group(1)} => &{ident.upper()},")
    out.append("    }")
    out.append("}\n")
    out += [block.rstrip("\n") + "\n" for block in blocks.values()]
    return "\n".join(out)


def patch_items_rs(items_rs: str, items: list[Item]) -> str:
    for item in items:
        items_rs = upsert_line(items_rs, "item_generator", "item_enum", rf"^\s*{item.variant}\s*,", f"    {item.variant},")
        items_rs = upsert_line(
            items_rs, "item_generator", "item_all", rf"ItemId::{item.variant}\s*,", f"            ItemId::{item.variant},"
        )
    return items_rs


def load(items_csv: Path, effects_csv: Path, existing_ids: set[str]) -> tuple[list[Item], Report]:
    report = Report()
    item_rows = read_csv(items_csv, ITEM_COLUMNS, report, legacy_hint="Item_name")
    effect_rows = read_csv(effects_csv, ("item_id", *EFFECT_COLUMNS), report)

    ids: dict[str, int] = {}
    names: dict[str, int] = {}
    for row in item_rows:
        ident, name = row.get("id"), row.get("name").casefold()
        if ident in ids:
            report.error(row.file, row.line, "id", ident, f"duplicate item id (first defined on line {ids[ident]})")
        elif ident:
            ids[ident] = row.line
        if name and name in names:
            report.error(row.file, row.line, "name", row.get("name"), f"duplicate item name (first used on line {names[name]})")
        elif name:
            names[name] = row.line

    by_owner = parse_effect_rows(effect_rows, "item_id", set(ids), report)
    known = set(ids) | existing_ids
    items: list[Item] = []
    seen: set[str] = set()
    for row in item_rows:
        if row.get("id") in seen:
            continue
        seen.add(row.get("id"))
        effects = by_owner.get(row.get("id"), [])
        item = parse_item(row, effects, report)
        if item is None:
            continue
        for comp in item.components:
            if comp == item.id:
                report.error(row.file, row.line, "components", comp, "an item cannot be its own component")
            elif comp not in known:
                report.error(row.file, row.line, "components", comp, "no item with this id (in the CSV or already generated)")
        ctx = effect_context(item)
        for effect in effects:
            if effect.trigger == "passive" and effect.effect_type != "stat_modifier":
                report.error(effect.row.file, effect.row.line, "effect_type", effect.effect_type, "passive item effects must be stat_modifier (use on_use / on_attack_hit for the rest)")
                continue
            if effect.trigger in NOT_EMITTED:
                report.warn(effect.row.file, effect.row.line, "trigger", effect.trigger, NOT_EMITTED[effect.trigger])
            rendered = effect_to_rust(effect, ctx, report)
            if rendered:
                item.effects.append(rendered)
        items.append(item)
    return items, report


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    repo_default = Path(__file__).resolve().parents[1]
    parser.add_argument("items", type=Path, nargs="?", help="items CSV (default: data/items.csv)")
    parser.add_argument("effects", type=Path, nargs="?", help="item effects CSV (default: data/item_effects.csv)")
    parser.add_argument("--repo-root", type=Path, default=repo_default, help="repository root (default: parent of scripts/)")
    parser.add_argument("--check", action="store_true", help="validate the CSVs without writing anything")
    parser.add_argument("--dry-run", action="store_true", help="print the generated Rust instead of writing it")
    args = parser.parse_args()

    repo = args.repo_root.resolve()
    items_csv = args.items or repo / "data" / "items.csv"
    effects_csv = args.effects or repo / "data" / "item_effects.csv"
    generated_path = repo / "src" / "item_catalog.rs"
    items_path = repo / "src" / "items.rs"

    blocks = read_blocks(generated_path, "item")
    items, report = load(items_csv, effects_csv, set(blocks))

    # Every ItemId variant must end up with a definition, or the match won't compile.
    items_rs = items_path.read_text(encoding="utf-8")
    covered = {to_pascal_case(i) for i in blocks} | {item.variant for item in items}
    enum_body = region_body(items_rs, "item_generator", "item_enum")
    for variant in re.findall(r"^\s*([A-Z][A-Za-z0-9]*)\s*,", enum_body, re.MULTILINE):
        if variant not in covered:
            report.error(str(items_csv), None, "id", None, f"ItemId::{variant} has no definition; add a row for it")

    report.fail_if_errors()
    report.print()
    print(f"Validated {len(items)} item(s) with {sum(len(i.effects) for i in items)} effect row(s).")
    if args.check:
        return 0

    for item in items:
        verb = "update" if item.id in blocks else "add"
        print(f"  {verb}: {item.id} → ItemId::{item.variant} ({item.cost}g, effects={len(item.effects)})")
        blocks[item.id] = item_static(item)
    generated = render_generated(blocks)
    items_rs = patch_items_rs(items_rs, items)

    if args.dry_run:
        print(generated)
        print("Dry run — no files written.")
        return 0
    generated_path.write_text(generated, encoding="utf-8")
    rustfmt(generated_path)
    items_path.write_text(items_rs, encoding="utf-8")
    print(f"Wrote {generated_path.relative_to(repo)} and updated {items_path.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
