//! Generated by `scripts/ItemGenerator.py` from `data/items.csv` and
//! `data/item_effects.csv` — edit the CSVs and re-run the generator.

#[allow(unused_imports)]
use crate::abilities::definition::{
    AbilityEffect, AbilityEffectEntry, AbilityTrigger, AreaCenter, AreaRadius, Attribute,
    DisplacementKind, EffectScaling, EffectTarget, PassiveStat, RankValue, StatusSpec, TargetTeam,
};
#[allow(unused_imports)]
use crate::components::DamageType;
#[allow(unused_imports)]
use crate::items::{ItemDefinition, ItemId, ItemRarity, ItemType, StatusKind};

pub fn definition(id: ItemId) -> &'static ItemDefinition {
    match id {
        ItemId::IronBracer => &IRON_BRACER,
        ItemId::SwiftBoots => &SWIFT_BOOTS,
        ItemId::ManaCrystal => &MANA_CRYSTAL,
        ItemId::BladeOfAsh => &BLADE_OF_ASH,
        ItemId::AegisCharm => &AEGIS_CHARM,
        ItemId::VialOfLight => &VIAL_OF_LIGHT,
        ItemId::StormRod => &STORM_ROD,
        ItemId::WardstoneCloak => &WARDSTONE_CLOAK,
        ItemId::HeartwoodBand => &HEARTWOOD_BAND,
        ItemId::SparkPendant => &SPARK_PENDANT,
        ItemId::RecipeHeartwoodBand => &RECIPE_HEARTWOOD_BAND,
        ItemId::RecipeSparkPendant => &RECIPE_SPARK_PENDANT,
    }
}

// <item:iron_bracer>
static IRON_BRACER: ItemDefinition = ItemDefinition {
    id: ItemId::IronBracer,
    name: "Iron Bracer",
    short_label: "IB",
    item_type: ItemType::Armor,
    cost: 300,
    sell_value: 150,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.55, 0.55, 0.6],
    description: "+100 HP, +4 Armor",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MaxHealth,
                amount: RankValue::fixed(100.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::Armor,
                amount: RankValue::fixed(4.0),
            },
        },
    ],
};
// </item:iron_bracer>

// <item:swift_boots>
static SWIFT_BOOTS: ItemDefinition = ItemDefinition {
    id: ItemId::SwiftBoots,
    name: "Swift Boots",
    short_label: "SB",
    item_type: ItemType::Utility,
    cost: 450,
    sell_value: 225,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.35, 0.7, 0.45],
    description: "+65 Move Speed",
    effects: &[AbilityEffectEntry {
        trigger: AbilityTrigger::Passive,
        target: EffectTarget::Caster,
        effect: AbilityEffect::PassiveStat {
            stat: PassiveStat::MoveSpeed,
            amount: RankValue::fixed(65.0),
        },
    }],
};
// </item:swift_boots>

// <item:mana_crystal>
static MANA_CRYSTAL: ItemDefinition = ItemDefinition {
    id: ItemId::ManaCrystal,
    name: "Mana Crystal",
    short_label: "MC",
    item_type: ItemType::Accessory,
    cost: 350,
    sell_value: 175,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.3, 0.45, 0.95],
    description: "+80 Mana, +4 Mana Regen",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MaxMana,
                amount: RankValue::fixed(80.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::ManaRegen,
                amount: RankValue::fixed(4.0),
            },
        },
    ],
};
// </item:mana_crystal>

// <item:blade_of_ash>
static BLADE_OF_ASH: ItemDefinition = ItemDefinition {
    id: ItemId::BladeOfAsh,
    name: "Blade of Ash",
    short_label: "BA",
    item_type: ItemType::Weapon,
    cost: 800,
    sell_value: 400,
    tier: 1,
    rarity: ItemRarity::Uncommon,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.85, 0.35, 0.25],
    description: "+18 Attack Damage, +15 Attack Speed",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::AttackDamage,
                amount: RankValue::fixed(18.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::AttackSpeed,
                amount: RankValue::fixed(15.0),
            },
        },
    ],
};
// </item:blade_of_ash>

// <item:aegis_charm>
static AEGIS_CHARM: ItemDefinition = ItemDefinition {
    id: ItemId::AegisCharm,
    name: "Aegis Charm",
    short_label: "AC",
    item_type: ItemType::Armor,
    cost: 700,
    sell_value: 350,
    tier: 1,
    rarity: ItemRarity::Uncommon,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.7, 0.65, 0.35],
    description: "+6 Armor, +5 Magic Resist",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::Armor,
                amount: RankValue::fixed(6.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MagicResist,
                amount: RankValue::fixed(5.0),
            },
        },
    ],
};
// </item:aegis_charm>

// <item:vial_of_light>
static VIAL_OF_LIGHT: ItemDefinition = ItemDefinition {
    id: ItemId::VialOfLight,
    name: "Vial of Light",
    short_label: "VL",
    item_type: ItemType::Utility,
    cost: 400,
    sell_value: 200,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 40.0,
    components: &[],
    color: [0.95, 0.9, 0.55],
    description: "Active: Heal 180 HP",
    effects: &[AbilityEffectEntry {
        trigger: AbilityTrigger::OnUse,
        target: EffectTarget::Caster,
        effect: AbilityEffect::Heal {
            amount: RankValue::fixed(180.0),
            scaling: EffectScaling::None,
        },
    }],
};
// </item:vial_of_light>

// <item:storm_rod>
static STORM_ROD: ItemDefinition = ItemDefinition {
    id: ItemId::StormRod,
    name: "Storm Rod",
    short_label: "SR",
    item_type: ItemType::Weapon,
    cost: 900,
    sell_value: 450,
    tier: 2,
    rarity: ItemRarity::Rare,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 30.0,
    components: &[],
    color: [0.45, 0.35, 0.95],
    description: "+12 AD. Active: 140 magic AoE",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::AttackDamage,
                amount: RankValue::fixed(12.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::AttackSpeed,
                amount: RankValue::fixed(10.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::OnUse,
            target: EffectTarget::UnitsInRadius {
                center: AreaCenter::Caster,
                radius: AreaRadius::Fixed(RankValue::fixed(143.0)),
                team: TargetTeam::Enemy,
            },
            effect: AbilityEffect::Damage {
                amount: RankValue::fixed(140.0),
                damage_type: DamageType::Magical,
                scaling: EffectScaling::None,
            },
        },
    ],
};
// </item:storm_rod>

// <item:wardstone_cloak>
static WARDSTONE_CLOAK: ItemDefinition = ItemDefinition {
    id: ItemId::WardstoneCloak,
    name: "Wardstone Cloak",
    short_label: "WC",
    item_type: ItemType::Armor,
    cost: 650,
    sell_value: 325,
    tier: 1,
    rarity: ItemRarity::Uncommon,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 35.0,
    components: &[],
    color: [0.4, 0.55, 0.5],
    description: "+80 HP, +4 MR. Active: +8 Armor 5s",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MaxHealth,
                amount: RankValue::fixed(80.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MagicResist,
                amount: RankValue::fixed(4.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::OnUse,
            target: EffectTarget::Caster,
            effect: AbilityEffect::ApplyStatus {
                status: StatusSpec::Modifier {
                    id: "wardstone_cloak_armor",
                    kind: StatusKind::Buff,
                    armor: RankValue::fixed(8.0),
                    magic_resist: RankValue::ZERO,
                    move_speed: RankValue::ZERO,
                    attack_damage: RankValue::ZERO,
                },
                duration: RankValue::fixed(5.0),
            },
        },
    ],
};
// </item:wardstone_cloak>

// <item:heartwood_band>
static HEARTWOOD_BAND: ItemDefinition = ItemDefinition {
    id: ItemId::HeartwoodBand,
    name: "Heartwood Band",
    short_label: "HB",
    item_type: ItemType::Armor,
    cost: 550,
    sell_value: 275,
    tier: 2,
    rarity: ItemRarity::Uncommon,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[ItemId::IronBracer, ItemId::RecipeHeartwoodBand],
    color: [0.405294, 0.452353, 0.558235],
    description: "+150 HP. +3 Armor. +2 Mana Regen",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MaxHealth,
                amount: RankValue::fixed(150.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::Armor,
                amount: RankValue::fixed(3.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::ManaRegen,
                amount: RankValue::fixed(2.0),
            },
        },
    ],
};
// </item:heartwood_band>

// <item:spark_pendant>
static SPARK_PENDANT: ItemDefinition = ItemDefinition {
    id: ItemId::SparkPendant,
    name: "Spark Pendant",
    short_label: "SP",
    item_type: ItemType::Accessory,
    cost: 750,
    sell_value: 375,
    tier: 2,
    rarity: ItemRarity::Rare,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 25.0,
    components: &[
        ItemId::ManaCrystal,
        ItemId::BladeOfAsh,
        ItemId::RecipeSparkPendant,
    ],
    color: [0.85, 0.55, 0.25],
    description: "+10 Attack Damage. +60 Mana. Active: deal 90 magical damage to nearby enemies and restore 40 mana",
    effects: &[
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::AttackDamage,
                amount: RankValue::fixed(10.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::Passive,
            target: EffectTarget::Caster,
            effect: AbilityEffect::PassiveStat {
                stat: PassiveStat::MaxMana,
                amount: RankValue::fixed(60.0),
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::OnUse,
            target: EffectTarget::UnitsInRadius {
                center: AreaCenter::Caster,
                radius: AreaRadius::Fixed(RankValue::fixed(117.0)),
                team: TargetTeam::Enemy,
            },
            effect: AbilityEffect::Damage {
                amount: RankValue::fixed(90.0),
                damage_type: DamageType::Magical,
                scaling: EffectScaling::None,
            },
        },
        AbilityEffectEntry {
            trigger: AbilityTrigger::OnUse,
            target: EffectTarget::Caster,
            effect: AbilityEffect::RestoreMana {
                amount: RankValue::fixed(40.0),
            },
        },
    ],
};
// </item:spark_pendant>

// <item:recipe_heartwood_band>
static RECIPE_HEARTWOOD_BAND: ItemDefinition = ItemDefinition {
    id: ItemId::RecipeHeartwoodBand,
    name: "Recipe: Heartwood Band",
    short_label: "R-HB",
    item_type: ItemType::Recipe,
    cost: 250,
    sell_value: 125,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.55, 0.5, 0.35],
    description: "Combines with components into Heartwood Band",
    effects: &[],
};
// </item:recipe_heartwood_band>

// <item:recipe_spark_pendant>
static RECIPE_SPARK_PENDANT: ItemDefinition = ItemDefinition {
    id: ItemId::RecipeSparkPendant,
    name: "Recipe: Spark Pendant",
    short_label: "R-SP",
    item_type: ItemType::Recipe,
    cost: 200,
    sell_value: 100,
    tier: 1,
    rarity: ItemRarity::Common,
    max_stack: 1,
    consumable: false,
    max_charges: None,
    cooldown: 0.0,
    components: &[],
    color: [0.6, 0.45, 0.25],
    description: "Combines with components into Spark Pendant",
    effects: &[],
};
// </item:recipe_spark_pendant>
